### ISSUE TITLE
Support `style='{'` keyword argument in `install()`

### ISSUE THREAD

**Issue by gyscos** [xolox/python-coloredlogs#17]
Just like `basicConfig` that it's supposed to replace, supporting `style='{'` for instance could be useful for the `install()` function.

**Comment by xolox** [comment]
Hi Alexandre and thanks for the suggestion. I've just released [coloredlogs 10.0](https://coloredlogs.readthedocs.io/en/latest/changelog.html#release-10-0-2018-05-13) which introduces support for the `style='{'` argument on Python 3.2+. I'm going to close this issue now because I think I correctly implemented your feature request, but if you run into any issues feel free to reopen this issue or open a new one.
