### ISSUE TITLE
I couldn't set the format through ColoredFormatter on Windows

### ISSUE THREAD

**Issue by mths0x5f** [xolox/python-coloredlogs#25]
This did not work as expected on Windows with Python 3.5
```python
formatter = coloredlogs.ColoredFormatter(fmt='%(asctime)s [%(levelname)s] %(message)s')
stream = logging.StreamHandler()
stream.setFormatter(formatter)
```

**Comment by xolox** [comment]
So what didn't work exactly? :-)

This issue's title implies that you were unable to change the default format, but it seems more likely to me that you got raw ANSI escape sequences on your terminal instead of colors?

Did you test if the `install()` function works? Because that function enables the colorama module on Windows to translate ANSI escape sequences into actual colors. If `install()` does indeed work, then you could add `colorama.init()` to your code sample to get it to work correctly.

Should I clarify this in the documentation?

**Comment by mths0x5f** [comment]
I'm sorry for so much time without response. You correctly interpreted the question, thanks for explaining the details. I think a little note in documentation would be great.

**Comment by xolox** [comment]
Hi Matheus and thanks for the confirmation,  I've added [a note](http://coloredlogs.readthedocs.io/en/latest/#coloredlogs.ColoredFormatter) to the documentation.
