### ISSUE TITLE
feature request: additional log level for 'success'

### ISSUE THREAD

**Issue by nrvale0** [xolox/python-coloredlogs#27]
I might implement this and send a PR but I want to make sure the PR would be welcome first...

It would be nice to have another loglevel, success, which would perhaps tweak the text and color of the output to bold and bright green so someone using our program has a very clear indication than an operation has succeeded.

**Comment by xolox** [comment]
Hi Nathan and thanks for the suggestion.

While the coloredlogs package defines styles for the custom log levels NOTICE, VERBOSE and SPAM you won't be able to use those custom log levels if you don't install the [verboselogs](https://github.com/xolox/python-verboselogs) package. This is because the verboselogs package modifies Python's logging module to enable the custom log levels.

While it has never occurred to me to add support for a SUCCESS log level, someone else has made the same suggestion in xolox/python-verboselogs/issues/4. If we can agree on a suitable integer level (in that issue) then I can add support for SUCCESS to verboselogs.

Once support for SUCCESS has been added to verboselogs we can come back to this issue to define styling for the new SUCCESS log level :slightly_smiling_face:.

**Comment by xolox** [comment]
I've just released coloredlogs 7.3 and verboselogs 1.7 which add support for the SUCCESS log level.

**Comment by HWiese1980** [comment]
Jumping on this train that has already left station years ago...

Is it possible to generally allow for custom log levels? Should be as simple as adding a mapping between an integer and a color...
