### ISSUE TITLE
AttributeError: 'Logger' object has no attribute 'success'

### ISSUE THREAD

**Issue by nrvale0** [xolox/python-coloredlogs#39]
In testing the new 'success' logger level, I'm getting the following with stack trace:

```pre
➜  ~ pip install --upgrade coloredlogs
Requirement already up-to-date: coloredlogs in ./.anyenv/envs/pyenv/versions/3.6.1/lib/python3.6/site-packages
Requirement already up-to-date: humanfriendly>=3.2 in ./.anyenv/envs/pyenv/versions/3.6.1/lib/python3.6/site-packages (from coloredlogs)
➜  ~ pip list | grep coloredlog
coloredlogs (7.3)
➜  ~ ipython                   
Python 3.6.1 (default, Jun  7 2017, 13:01:33) 
Type 'copyright', 'credits' or 'license' for more information
IPython 6.1.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: import coloredlogs, logging

In [2]: logger = logging.getLogger(__name__)

In [3]: coloredlogs.install(level='DEBUG')

In [4]: coloredlogs.install(level='DEBUG')

In [5]: logger.debug('foobar')
2017-08-08 06:40:05 namib __main__[6157] DEBUG foobar

In [6]: logger.success('foobar')
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-6-ec77b2ea1cba> in <module>()
----> 1 logger.success('foobar')

AttributeError: 'Logger' object has no attribute 'success'
```

For sanity's sake I grepped the source code and indeed the success level is in the DEFAULT_LEVEL_STYLES dict.

Also, this works:

```pre
In [1]: import coloredlogs, logging

In [2]: coloredlogs.level_to_number('debug')
Out[2]: 10

In [3]: coloredlogs.level_to_number('success')
Out[3]: 20
```

Not quite sure what to make of this...

**Comment by nrvale0** [comment]
```pre
➜  ~ pip list | grep logs
coloredlogs (7.3)
verboselogs (1.7)
```

**Comment by xolox** [comment]
There are two ways to use the `success()` method but both of them require more action from your side than just importing `logging` and `coloredlogs`, basically you need to enable `verboselogs`:

1. **Less invasive but requires some discipline:** Explicitly instantiate a logger of the [verboselogs.VerboseLogger](http://verboselogs.readthedocs.io/en/latest/api.html#verboselogs.VerboseLogger) type (instead of the [logging.Logger](https://docs.python.org/3/library/logging.html#logging.Logger) type) and use that in your Python code.

2. **More invasive but requires less discipline:** Make [verboselogs.VerboseLogger](http://verboselogs.readthedocs.io/en/latest/api.html#verboselogs.VerboseLogger) the default logger type by calling [verboselogs.install()](http://verboselogs.readthedocs.io/en/latest/api.html#verboselogs.install).

**Comment by nrvale0** [comment]
Thanks for adding 'success' and thanks for the fast response. 

It's been a couple of months since I last looked at my code which is using coloredlogs and, indeed, there is setup code for verboselogs in there as well. On this pass I read the 'Just Works portion of the coloredlogs docs and assumed it would detect and default to verboselogs. Thus my confusion. 

Thanks for the clarification.
