### ISSUE TITLE
Customize INFO log color

### ISSUE THREAD

**Issue by robinandeer** [xolox/python-coloredlogs#44]
Hey,

I've just started playing around with updating the format of the logs depending on if the program logs to a file (non-interactive) vs. a terminal (interactive).

For logging to file it works great but when I want to log just the message to STDERR, the info logs don't really stand out from anything printed to STDOUT. This can be confusing to users.

So I was wondering about options to control coloring of the output - is it possible to customize the style of different log levels? Perhaps I could style the INFO logs in "blue" to make them stand out more

Thanks for a great package! 📦

**Comment by xolox** [comment]
Hi Robin, thanks for your interest and sorry for not following up here earlier. Nowadays `coloredlogs` supports custom styles for different levels, the documentation [provides an example](https://coloredlogs.readthedocs.io/en/latest/api.html#changing-the-colors-styles). This functionality can be used to color `INFO` differently from standard output (although the defaults have remained the same since you originally posted this).
