### ISSUE TITLE
Option isatty=True not always working

### ISSUE THREAD

**Issue by pascal-hari** [xolox/python-coloredlogs#84]
# Detected issue
When passing the parameter `isatty=True` to the method `coloredlogs.install()` the logger does not always generate a colored output. 

# Conditions  
I use this option because I run on windows and use a git bash terminal. Since git bash is using pipes it's not detecting the terminal correctly with `sys.stdout.isatty()`.

# Expected behavior
I would expect with the `isatty=True` to the method `coloredlogs.install()` that the colored output is forced independent of `sys.stdout.isatty()`.

# Version
This has been discovered when running on version 14.0.

# More information on issue
Debugging the module has shown that the method [`terminal_supports_colors(stream)`](https://github.com/xolox/python-coloredlogs/blob/14.0/coloredlogs/__init__.py#L434) returns false and the use_colors gets deactivated. More debugging has shown that in there the `sys.stdout.isatty()` is called.   
Looking at [those lines](https://github.com/xolox/python-coloredlogs/blob/14.0/coloredlogs/__init__.py#L426-L434) there is no difference from `'isatty'=None` and `'isatty'=True`.

# Possible fix
For me changing [line 433](https://github.com/xolox/python-coloredlogs/blob/14.0/coloredlogs/__init__.py#L433) to `if use_colors is None:` solved the issue. But I cannot tell if this is a valid fix, since I do not know other use cases.

**Comment by dwardzinski-jsf** [comment]
I am also having this issue. Looking at the source code, it would appear that only `isatty=False` has any effect (forces colors to be disabled). As you mentioned, `isatty=True` and `isatty=None` both use terminal auto-detection, so setting `isatty=True` makes no difference. Your fix (changing line 433 to `if use_color is None:` would appear to be a valid fix, since it would make sense for `isatty=True` to force coloring regardless of whether the script thinks it's in an interactive terminal or not.

As for use cases, I've been having some issues with this since I'm calling my script through a job scheduler like cron. I've managed to find a workaround without changing the source code by calling `script -q -c 'python3 script.py'`, which tricks it into thinking it's being called through a terminal, but that itself caused other issues like causing `SIGTERM` intercepting to stop working properly.

**Comment by heni** [comment]
use could install my version locally, just executing command
`pip install -U git+https://github.com/heni/python-coloredlogs.git@fix/isatty-force-attribute`

**Comment by michael-o** [comment]
I basically have the same problem, but with a different usecase. My Python code runs a shared GitLab runner and I do pass `isatty=True` and expected that colors are forced even if we are not attached to a terminal, but still autodetection works. I'd expect that `True` would force/override detection.

**Comment by michael-o** [comment]
@heni Your patch works for me in the GitLab runner.

**Comment by xolox** [comment]
Hi all and thanks for the feedback. I've just published coloredlogs [release 14.1](https://coloredlogs.readthedocs.io/en/latest/changelog.html#release-14-1-2020-12-10) which fixes this issue.
